#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#


# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#Customize to your needs...
for config_file ($HOME/.yadr/zsh/*.zsh) source $config_file

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
export ANDROID_HOME=/usr/local/Cellar/android-sdk/24.4.1_1/

###-tns-completion-start-###
if [ -f /Users/ajish/.tnsrc ]; then
    source /Users/ajish/.tnsrc
fi
###-tns-completion-end-###

source /usr/local/share/antigen/antigen.zsh


test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
